name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version Bump Type (major/minor/patch)'
        required: true
        default: 'patch'

jobs:
  release:
    if: github.ref == 'refs/heads/main' && github.repository == 'gayathrir11/test-github-actions'
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.LOGIN_GITHUB_TOKEN }}
       - name: Configure git
         run: |
          git config --global user.email "rallapallegayathrichowdary@gmail.com"
          git config --global user.name "Gayathri Rallapalle"
      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
          # The registry URL and `NODE_AUTH_TOKEN` are needed for `npm publish` to work properly
          # See https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm
          registry-url: 'https://registry.npmjs.org'
      - name: Compute next development version
        run: |
          releaseVersion=${{ github.event.inputs.bump_type }}
          n=${releaseVersion//[!0-9]/ }
          a=(${n//\./ })
          nextPatch=$((${a[2]} + 1))
          developmentVersion="${a[0]}.${a[1]}.${nextPatch}-SNAPSHOT"
          echo "DEVELOPMENT_VERSION=${developmentVersion}" >> $GITHUB_ENV
      - name: Prepare release
        run: npm run ${{ github.event.inputs.bump_type }}
      - name: Push Changes
        run: |
          git add .
          git commit -m "Release commit"
          git push origin main

      - name: Install dependencies and build project
        run: |
          npm install
          npm install -g @vscode/vsce
          tsc
      - name: Publish to NPM
        run: npm publish --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
